import Foundation

/// Ready-made shortcuts so setup is one tap instead of a nine-step recipe.
///
/// The app bundles signed `.shortcut` files generated by `tools/shortcuts/build.py`
/// (signed with `shortcuts sign --mode anyone`, so any device can import them). Handing
/// one to the Shortcuts app through the share sheet imports it: the user chooses
/// Shortcuts, then taps Add Shortcut. Regenerate the files whenever the recipe changes,
/// and keep `HelpView.manualRecipeSteps` in step with them.
///
/// The iCloud links are a fallback for the same recipes. They are snapshots: after any
/// change, share the shortcut again and replace the URL.
enum KlypstLinks {
    /// The one-press recipe for the Action Button (text, links and images):
    /// Get Clipboard → Get Images from Input → If images: Pick a Clip (Save Image First) /
    /// Otherwise: Pick a Clip (Save First: Clipboard) → If result has any value: Copy to Clipboard.
    static var actionButtonShortcutFile: URL? {
        Bundle.main.url(forResource: "Klypst", withExtension: "shortcut")
    }

    /// Pick an Image Clip → Copy to Clipboard. Optional: pastes an image without opening
    /// Klypst, for Back Tap or a Control Center shortcut button.
    static var imageShortcutFile: URL? {
        Bundle.main.url(forResource: "Klypst Images", withExtension: "shortcut")
    }

    static let actionButtonShortcut: URL? = URL(string: "https://www.icloud.com/shortcuts/19bbb43d509a41b79a772394531d95eb")
    static let imageShortcut: URL? = URL(string: "https://www.icloud.com/shortcuts/41380939ae51405f958fe4af6be01063")
}
